version: 0.2
phases: 
  install:
    commands: 
      - aws cloudformation package --template-file template.yaml --s3-bucket lambda-ci-cd-demo-bucket-sf --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml