version: 0.2
phases: 
  installl:
    runtime-versions:
      python: 3.7
      commands:
        - aws cloudformation package --template-file template.yml --s3-bucket lambda-ci-cd-demo-bucket --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml