AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CI/CD Lambda Test
Resources:

  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: info.handler
      CodeUri: ./Lambda
      AutoPublishAlias: live
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      DeploymentPreference: 
        Type: All-at-once #Canary10Percent5Minutes
        Alarms:
          - !Ref AliasErrorMetricGreaterThanZeroAlarm
          - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
      Events: 
        ChallengesAPI:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          REGION: us-east-1

  AliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreatherThanThreshold
      Dimension:
        - Name: Resource
          Value: !Sub "${HelloWorld}:live"
        - Name: FunctionName
          Value: !Ref HelloWorld
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      
  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "Lambda Function Error > 0"
      ComparisonOperator: GreatherThenThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${HelloWorld}:live"
        - Name: FunctionName
          Value: !Ref HelloWorld
        - Name: ExecutedVersion
          Value: !GetAtt HelloWorld.Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      NameSpace: AWS/Lambda
      Statistics: Sum
      Threshold: 0


            

        
             


          



      
  
